유저 정보를 조회/수정하는 API
minyoungbaek/nest-study-eventory pull request #10
Opened 2024-11-21 05:19 UTC by minyoungbaek

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 비밀번호 변경 API
- 유저 정보 조회 API
- 유저 정보를 수정하는 API

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Swagger에서 테스트 해볼때 authorize에 유저 access token을 넣는게 맞나요??

2024-11-21 05:53 UTC, worjs requested changes

2024-11-21 05:53 UTC, worjs commented on src/user/type/user-data.type.ts
> +  cityId?: number | null;
이건 user을 조회하고 나온 데이터를 그대로 매핑하는 타입입니다.
근데 db에는 undefined가 없어서, nullable하게만 하면 될거같아요.

```
const user = this.prisma.user.findUnique({
      where: {
        id: userId,
      },
      select: {
        id: true,
        email: true,
        name: true,
        birthday: true,
        cityId: true,
        categoryId: true,
      },
    });
```

이렇게 하고 user 변수에 마우스 올려보시면 어떤 타입이 실제로 오는건지 확인할 수 있어요.

2024-11-21 05:53 UTC, worjs commented on src/user/user.controller.ts
> +  @HttpCode(200)
Get은 200이 디폴트!

2024-11-21 05:53 UTC, worjs commented on src/user/user.controller.ts
> +  @HttpCode(200)
안붙여도 됩니다.

2024-11-21 05:53 UTC, worjs commented on src/user/user.controller.ts
> +    @Param('userId') userId: number,
`ParseIntPipe`

2024-11-21 05:53 UTC, worjs commented on src/user/user.service.ts
> +      }
이거 빼도 같은 결과가 나올 것 같은데요?

2024-11-21 05:53 UTC, worjs commented on src/user/user.service.ts
> +      }
만약에 cityId가 null이 되면 어떻게 되나요?

2024-11-21 05:53 UTC, worjs commented on src/user/dto/user.dto.ts
> +  cityId?: number | null;
여기도 undefined X

2024-11-21 08:35 UTC, minyoungbaek commented on src/user/type/user-data.type.ts
> +  cityId?: number | null;
아 그렇네요 알겠습니다!

2024-11-21 08:49 UTC, minyoungbaek commented on src/user/user.service.ts
> +      }
그렇네요 이 부분은 지우겠습니다..! 테스트 해보니까 cityId null로 update 해도 잘 되는거 같습니다 아마도..

2024-11-21 09:35 UTC, worjs commented on src/user/user.service.ts
> +      }
어라 현재 코드에서 cityId null로 주면 NotFoundException 뱉지 않나요?

2024-11-21 09:37 UTC, worjs commented on src/user/user.service.ts
> +      }
아 그리구 JS에서는 등호 세개 쓰셔야 값비교예요 !

2024-11-21 09:37 UTC, worjs commented on src/user/user.service.ts
> +      }
바로 위에도 != 가 있더라구요

2024-11-21 09:38 UTC, worjs requested changes

2024-11-21 09:38 UTC, worjs commented on src/user/user.service.ts
> +      const validCityId = await this.userRepository.isCityExist(payload.cityId);
흠 여기 빨간줄 정말 안뜨나요? payload.cityId가 number | null 타입일건데

2024-11-21 14:13 UTC, minyoungbaek commented on src/user/user.service.ts
> +      }
아 테스트 했을때는 if(payload.cityId == 0) 지우고 한거라 가장 최근 커밋 기준으로는 되는거 같습니다..!

2024-11-21 14:17 UTC, minyoungbaek commented on src/user/user.service.ts
> +      const validCityId = await this.userRepository.isCityExist(payload.cityId);
<img width="640" alt="Screenshot 2024-11-21 at 11 14 59 PM" src="https://github.com/user-attachments/assets/27f8219d-8cdf-401a-831d-c4c1a53d0ae7">

일단은 안뜨는거 같습니당..

2024-11-21 14:19 UTC, worjs requested changes

2024-11-21 14:19 UTC, worjs commented on src/user/payload/update-user.payload.ts
> +  cityId?: number | null;
추가로 실제로 nullable한 값이니까
nullable:true 넣어주는걸로!
그래야 docs에서 저 두 값만 null이 가능하다는걸 표현할 수 있어요.

2024-11-21 14:19 UTC, worjs commented on src/user/user.service.ts
> +      }
!==로 바꿔보시면 빨간줄 나옵니다ㅎㅎ 확인하셔서 수정 부탁드림!

2024-11-21 14:20 UTC, worjs commented on src/user/user.service.ts
> +      const validCityId = await this.userRepository.isCityExist(payload.cityId);
!==로 바꿔보시면 빨간줄 나옵니다ㅎㅎ 확인하셔서 수정 부탁드림!

2024-11-21 14:23 UTC, minyoungbaek commented on src/user/user.service.ts
> +      const validCityId = await this.userRepository.isCityExist(payload.cityId);
아 그렇네요ㅋㅋㅎ 수정하겠습니다!

2024-11-22 04:39 UTC, worjs approved these changes

2024-11-22 07:07 UTC, merged