클럽을 생성하는 API
minyoungbaek/nest-study-eventory pull request #23
Opened 2024-11-25 13:47 UTC by minyoungbaek

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 클럽을 생성하는 API입니다.

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-25 15:18 UTC, worjs requested changes

2024-11-25 15:18 UTC, worjs commented on src/club/club.repository.ts
> +    });
얘도 clubJoin 행 넣어줘야 할듯!

2024-11-26 04:44 UTC, worjs approved these changes
하나만 코멘트 확인해주시고 ㄱㄱ!

2024-11-26 04:44 UTC, worjs commented on src/club/club.repository.ts
> +            status: 'ACCEPTED',
Enum으로 관리하기로 했으니까, 직접 String을 쓰는 것 보다는
`ClubStatus.ACCEPTED`였나? 이런 식으로 enum으로 넣는게 좋아보이네요

2024-11-26 04:59 UTC, minyoungbaek commented on src/club/club.repository.ts
> +            status: 'ACCEPTED',
아 그렇게도 사용이 가능했군요..! 수정하겠습니다

2024-11-26 05:11 UTC, merged