클럽을 수정하는 API
minyoungbaek/nest-study-eventory pull request #24
Opened 2024-11-25 14:15 UTC by minyoungbaek

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- PATCH를 이용한 클럽을 수정하는 API입니다.

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-25 15:21 UTC, worjs requested changes

2024-11-25 15:21 UTC, worjs commented on src/club/club.service.ts
> +      maxPeople: payload.maxPeople,
기존 가입자 수 관련한 검증이 필요할 것 같네요.

2024-11-25 15:21 UTC, worjs commented on src/club/club.service.ts
> +    user: UserBaseInfo,
혹시 리드 변경하는 기능은 별도의 api로 만드실 계획이신가요

2024-11-26 04:25 UTC, minyoungbaek commented on src/club/club.service.ts
> +    user: UserBaseInfo,
네 클럽장 위임하는 API를 따로 만들 생각이었습니다..!

2024-11-26 04:42 UTC, worjs commented on src/club/club.service.ts
> +    user: UserBaseInfo,
넵 좋습니다

2024-11-26 15:59 UTC, worjs approved these changes
LGTM!

2024-11-27 02:51 UTC, merged