클럽을 삭제하는 API
minyoungbaek/nest-study-eventory pull request #25
Opened 2024-11-26 13:41 UTC by minyoungbaek

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 클럽을 삭제하는 API입니다.

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-26 16:18 UTC, worjs requested changes
클럽 삭제는 꽤 복잡합니다.

사실 이 코드에서도 고려가 된건 아닌데, 클럽 전용 모임을 어떻게 둘 것인가... 하는 문제가 남아있죠.
클럽 전용 모임을 생성해둔 상태에서 클럽을 삭제하려고 하면 FK 제약 때문에 에러가 뜰겁니다.

이 부분에 대해서 고민해보고 의견 주시면 도와드릴게요!

2024-11-27 02:46 UTC, minyoungbaek commented
제가 너무 단순하게 생각했었네요..ㅋㅋㅎ 아직 모임 관련된 부분을 고려 안했었는데 한번 고민해보겠습니다!

2024-12-04 16:44 UTC, minyoungbaek commented
일단 soft delete 방식으로 클럽 삭제를 구현해봤습니다! 그리고 클럽 전용 모임 관련해선 이렇게 처리할까 생각중입니다..

- 시작되지 않았거나 진행중인 클럽 전용 모임 삭제
- 종료된 클럽 전용 모임은 그대로 둠 (유저가 지금까지 참여한 모임 조회가 가능해야함) 대신 clubId는 null로 변경?

2024-12-05 01:03 UTC, worjs commented
- 사실 모임 수정/삭제의 요건도 모임이 시작했냐, 아니냐니까, 진행 중을 별도로 하는 것 보단, 진행 중도 삭제랑 똑같이 유지하는걸로 가면 좋을 것 같습니다.
- 이렇게 클럽이 날아갔는데 이미 진행된 모임의 경우에는 유지하는 방향이 저도 좋다고 보고, 대신 기존 모임은 전체공개, 클럽 모임은 클럽원 공개였다면, (구) 클럽 모임은 당시 참가자만 볼 수 있도록 처리해봅시다. 거기 딸린 리뷰 역시 참가자들만 볼 수 있도록요!
- club을 soft delete하는 목적을 자세히 말씀해주실 수 있을까요? 어느쪽으로든 구현은 가능합니다.

2024-12-09 11:29 UTC, minyoungbaek commented
음 일단은 FK 제약 문제랑 클럽 전용 모임이 모두 삭제되는게 아니라서 이후에도 클럽 정보가 필요할거 같아서 soft-delete이 좋을거 같았는데 이번에 모임, 리뷰쪽도 건드려 보니까 딱히 의미있지는 않았네요ㅠ 일단은 클럽 삭제 후 모임, 리뷰 조회 관련해서 수정을 좀 했는데 테스트를 해보니까 다른건 괜찮은데 모임 조회할 때 (특히 (구) 클럽 모임 조회) 조금 문제가 있기는 하네요.. OR, AND가 중첩되면서 좀 지저분해진거 같아서 이게 아니라 아예 스키마 변경을 통해서 모임에도 status 같은걸 추가해줘야하는 생각도 들었습니다

그래서 일단은 피드백 먼저 받고 다시 한번 수정해보겠습니다!

2024-12-09 12:39 UTC, worjs requested changes
좀 더 명확하게 가이드라인을 드릴게요!

결국 모임의 종류가 3개가 되는겁니다.

1. 그냥 모임 -> 모두 조회 가능
2. 클럽 모임 -> 클럽원만 조회 가능
3. 아카이브 모임(클럽 모임이었는데 이미 시작되었기 때문에 살려두는 모임) -> 참가자만 조회 가능

getEvents를 했을 때
처리를 나눠서 할 필요가 있습니다.
1. Query를 통해 받는 검색 조건
2. 검색 끝나고 받은 Event의 조회 권한 체크

1번은 Repository에서 마무리하고, 권한 체크는 서비스에서 진행한다고 생각하시면 됩니다.

그럼 일단 검색해서 권한이 있건 없건 조회를 하고, 서비스에서는 각 모임에 대해 유저가 권한이 있는지를 확인해서 최종 필터링을 마치면 됩니다.

권한을 확인하는 방법은 각 모임을 먼저 3가지에 맞게 분류한 다음, 그 모임의 권한에 따라 유저가 클럽원이 맞는지, 해당 모임의 참가자인지를 조사하면 되겠습니다.

여기서 고려해야 할 점은, 반복문 내에 쿼리를 넣는 방식은 금지라는 점ㅎㅎ

2024-12-09 12:39 UTC, worjs commented on src/club/club.repository.ts
> +      }),
얘도 시작 안한 애들만 지우는거라 startTime 조건 들어가야할 것 같습니다!

2024-12-09 12:39 UTC, worjs commented on src/club/club.repository.ts
> +      }),
얘는 clubId를 null로 박지말고 그대로 둬야
이게 삭제된 클럽의 클럽 모임인지 나중에 구분히 가능하지 않나요??

지금 이걸 null로 박아버리면 일반 모임이랑 구분이 힘들 것 같네요?
아 그래서 status를 추가할까 고민이 된다고 하신거군요

soft delete를 한다 -> fk를 끊지 않겠다
라는 의미인데 soft delete를 하게 된 원흉(?)인 event에서 fk를 끊어버리면 의미가 없죠ㅎㅎ

2024-12-09 12:39 UTC, worjs commented on src/event/event.repository.ts
> +        ],
저를 죽여주세여.....

2024-12-09 15:06 UTC, minyoungbaek commented on src/event/event.repository.ts
> +        ],
ㅋㅋㅋㅋㅠ 어떻게든 돌아가게 하려고 하다보니..

2024-12-09 15:07 UTC, minyoungbaek commented
이것도 맞게한지는 잘 모르겠지만 일단 모임 조회 부분 다시 작성해봤습니다..!

2024-12-10 03:15 UTC, worjs requested changes
리뷰쪽도 부탁드립니다!
모임쪽은 굳!

2024-12-10 03:15 UTC, worjs commented on src/event/event.service.ts
> +      .map((event) => event.clubId as number);
이거 as number 안쓰면 빨간줄 났었나요

2024-12-10 07:45 UTC, minyoungbaek commented on src/event/event.service.ts
> +      .map((event) => event.clubId as number);
네 clubIds에 빨간줄 뜨더라고요..

2024-12-12 11:31 UTC, minyoungbaek commented
리뷰도 수정 완료했습니다!

2024-12-13 00:50 UTC, worjs approved these changes
고생하셨습니다!

2024-12-13 01:23 UTC, merged