클럽을 조회하는 API
minyoungbaek/nest-study-eventory pull request #26
Opened 2024-11-28 16:26 UTC by minyoungbaek

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 클럽 정보 조회, 여러 클럽 정보 조회, 유저가 가입한 클럽 정보 조회하는 API입니다.

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-28 16:33 UTC, minyoungbaek commented
테스트를 해보니까 유저가 참여한 클럽을 조회하는 메서드에서 에러가 발생하네요..? 이벤트에서 구현한 동일한 메서드도 다시 테스트 해보니까 똑같은 에러가 뜨던데 다른거랑 똑같이 user.id를 넘겨주는건데 왜 얘만 에러가 발생하는지 모르겠습니다..
```
{
  "message": "Validation failed (numeric string is expected)",
  "error": "Bad Request",
  "statusCode": 400
}
```

2024-11-29 02:08 UTC, worjs approved these changes

2024-11-29 02:09 UTC, worjs requested changes

2024-11-29 02:09 UTC, worjs commented on src/club/club.repository.ts
> +  }
신청만해도 MyClubs 맞나요??

2024-11-29 02:10 UTC, worjs commented
어 근데 저거 아마 ParseIntPipe fail되면 나오는 메세지일텐데 GET /clubs/me 에서 뜨신다구요?

2024-11-29 05:48 UTC, minyoungbaek commented on src/club/club.repository.ts
> +  }
앗 그걸 빼먹었네요.. 수정하겠습니다!

2024-11-29 05:53 UTC, minyoungbaek commented
넵.. 찾아보니까 그냥 controller에서 메서드 순서만 바꿔도 해결될때가 있다고 하던데 그걸로도 해결은 안되더라고요

2024-11-29 07:16 UTC, worjs commented
아 맞네 저거 라우팅 문제입니다
/:id보다 /me를 위에 둬보실래요?

저게 /:id가 위에 잇으면 me를 id로 인식해서 /:id로 보내버릴 수 있어요

2024-11-29 07:26 UTC, minyoungbaek commented
오 이제 잘되네요..!

2024-11-29 08:42 UTC, worjs commented
고고고
그 Club 조회하면 클럽원들 Id 리턴할 수 있게 ClubDto도 변경하는거 나중에 PR로 한번 만들어주세요!

2024-11-29 08:42 UTC, worjs approved these changes

2024-11-29 14:12 UTC, merged