유저가 클럽에서 탈퇴하는 API
minyoungbaek/nest-study-eventory pull request #29
Opened 2024-11-30 03:53 UTC by minyoungbaek

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 유저가 클럽에서 탈퇴하는 API입니다.

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-30 03:54 UTC, minyoungbaek commented
유저가 가입 신청 승인되기 전에 PENDING 상태에서 가입을 취소하는 API를 따로 구현하는게 좋을까요??

2024-12-02 16:25 UTC, worjs requested changes

2024-12-02 16:25 UTC, worjs commented on src/club/club.repository.ts
> +  }
이제 클럽 탈퇴부터는 살짝 더 고려할 게 많습니다.

탈퇴하는 이 유저는 어떤 클럽 모임의 호스트일수도 있고, 어떤 클럽 모임의 참가자일 수도 있습니다. 그러면 미리 모임들에 가입해놨다면, 탈퇴 이후에도 클럽 모임을 개설하거나, 참가할 수 있는 상황이 벌어지죠. 
따라서 아래와 같이 처리해주세요!

1. 클럽 모임의 호스트이건, 참가자이건 상관 없이, 이미 시작된 모임이라면 그대로 둡니다.
2. 이미 시작된 클럽 모임은 클럽을 나간 이후에도 조회할 수 있어야 합니다.(참가자 자격)
3. 시작되지 않은 클럽 모임의 호스트였다면, 해당 모임이 삭제됩니다.
4. 시작되지 않은 클럽 모임의 참가자라면, 해당 모임에서 나가집니다.

2024-12-03 03:49 UTC, minyoungbaek commented on src/club/club.repository.ts
> +  }
그렇네요.. 다시 한번 고민해보고 수정하겠습니다!

2024-12-03 05:23 UTC, kevvnbk commented on src/club/club.repository.ts
> +  }
일단 클럽 모임 관련된 부분을 아직 아예 반영을 안했어서 클럽 삭제나 탈퇴 구현하기 전에 기존 event api 수정사항들만 따로 pr 올리겠습니다!

2024-12-03 05:40 UTC, worjs commented on src/club/club.repository.ts
> +  }
좋습니다~~

2024-12-03 05:40 UTC, worjs commented
아 그리고 신청 취소 기능도 생각해보니 있는게 맞겠네요

2024-12-13 00:52 UTC, worjs approved these changes

2024-12-13 01:26 UTC, merged