모임을 생성하는 API
minyoungbaek/nest-study-eventory pull request #3
Opened 2024-11-03 09:49 UTC by minyoungbaek

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 모임을 생성하는 POST /events 메소드를 구현합니다.

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- #14 과제 설명에는 모임이 3개의 상태를 가진다고 하는데 그걸 어떻게 구현해야될지 모르겠네요.. 일단 피드백을 받아야 다른 메소드 시도를 해볼 수 있을거 같습니다..
- 모임을 생성하면 id는 그냥 랜덤으로 자동 지정되는건가요? 

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-03 13:39 UTC, worjs requested changes
안녕하세요! 리뷰 남겨드렸습니다~

모임을 생성할 때 별도로 status를 저장하고 있지 않는데, 이는 저장할 필요가 없기 때문입니다. startDate, endDate, 그리고 지금 시간과의 관계를 통해서 결정할 수 있습니다.

근데 이번 구현에는 status가 필요없을거얘요ㅎㅎ

2024-11-03 13:39 UTC, worjs commented on src/event/event.service.ts
> +  }
검증 로직이 빠져있네요! 에러코드 404, 409의 대상이 되는 예외사항들을 잡아서 처리해줘야합니다.

2024-11-03 13:39 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +  cityId!: number;
이 코드는 카테고리나 지역이 더 추가되거나 시스템이 바뀌게 된다면 같이 수정해줘야 하는 코드가 되겠네요!
나중에 서비스가 커지면 개발자가 실수할 여지가 생기게 됩니다.
다른 방식으로 해당 ID가 실제로 있는 유효한 ID인지 검증할 방법이 있을 것 같네요!

2024-11-03 13:39 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +  cityId!: number;
아 그리고 현재 DB에서 ID는 객체를 추가하면 1부터 자동으로 숫자로 부여하는 auto_increment방식으로 id를 생성하고 있습니다.

2024-11-03 13:40 UTC, worjs commented
보니까 충돌이 있는 것 같네요?
로컬에서 메인 브랜치 rebase하고 다시 푸시해보면 좋을듯!

2024-11-03 15:50 UTC, minyoungbaek commented on src/event/event.service.ts
> +  }
넵 반영하겠습니다!

2024-11-03 15:51 UTC, minyoungbaek commented on src/event/payload/create-event.payload.ts
> +  cityId!: number;
아 그렇군요..! 더 추가될 수 있다는걸 고려 못했네요 수정하겠습니다!

2024-11-04 08:37 UTC, worjs requested changes
좋습니다~

이전 리뷰에서 제가 실수로 놓쳤었는데, 요구사항에 호스트가 모임을 만들 때 본인도 그 모임에 가입된 것으로 해야 한다는 부분이 있었습니다! 해당 부분에 대한 구현이 이루어져야 할 것 같아요.

추가로 지금 빌드가 실패한 것으로 나오는데, 한번 실행해보시면 에러가 잡힐거예요. 그거까지 잡아서 다시 올리고 리뷰 요청해주세요! 오른쪽에 리뷰 재요청 버튼 있습니다~

2024-11-04 08:37 UTC, worjs commented on src/event/event.repository.ts
> +  }
isHostIdExist라는 이름을 보면 host에 관한 체킹을 할때만 써야할 것 같은데, 막상 동작은 어떤 userId가 있는지 없는지 존재하는 코드인 것 같아요. isUserIdExist가 더 적합하지 않을까요?

2024-11-04 08:39 UTC, worjs commented on src/event/event.repository.ts
> +  }
아 그리구 city랑 category 검증하는 함수의 이름은 isCategoryExist고 isCityExist인데, 얘는 isHostIdExist입니다.

함수 이름의 일관성이 떨어져서, 하나로 통일하면 좋을 것 같네요.

2024-11-04 11:14 UTC, minyoungbaek commented on src/event/event.repository.ts
> +  }
확인했습니다! 감사합니다

2024-11-04 12:37 UTC, minyoungbaek commented
호스트를 자동으로 모임에 가입하는걸 어떻게어떻게 찾아서 구현한거 같기는한데, 정확한 원리는 이해를 못한거 같네요.. 모임을 생성해야 고유 이벤트id가 생성이 되는거 같은데 그럼 모임 생성과 동시에 새로 만들어진 이벤트id를 바로 eventjoin에 넣을 수 있게해주는건가요??

2024-11-04 14:04 UTC, worjs approved these changes
LGTM! 좋습니다

호스트도 가입되게 할려면 event를 생성한 후, 그 id와 유저의 id를 가지고 다시 eventJoin을 생성해야 합니다. 위의 방식으로 구현해도 되는데, prisma에서는 relation query라고 해서 저렇게 연관된 테이블까지 바로 데이터를 생성하도록 할 수 있습니다!

프리즈마 관련해서는 4주차에 다뤄볼 생각이예요 고생하셨습니다!

2024-11-04 14:11 UTC, merged