모임을 수정/삭제하는 API
minyoungbaek/nest-study-eventory pull request #6
Opened 2024-11-10 12:34 UTC by minyoungbaek

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 모임을 수정하는 API
- 모임을 삭제하는 API

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- 모임을 수정할때 categoryId나 cityId에 존재하지 않는 id를 넣으면 해당 카테고리/도시가 존재하지 않는다는 예외처리가 잘 되는데 0을 값으로 넣으면 에러가 뜨네요.. 모임 생성할때는 0도 예외처리가 잘 됐는데 수정할때는 왜 다른지 잘 모르겠습니다

2024-11-10 16:12 UTC, worjs requested changes
적어주신 코드는 거의 리뷰할 부분이 없네요!

대신 Patch에서 시간 관련한 로직들에서 더 고려해야하는 예외사항들이 있습니다.

예를 들어 startDate 하나만 변경 요청을 보냈는데 이미 있는 endtime과의 정합성이 안맞는 경우라던가...

그거만 수정하면 될 것 같네요

2024-11-11 06:02 UTC, minyoungbaek commented
예외처리 추가했습니다! 그런데 테스트를 해보니까 모임을 수정할때 categoryId나 cityId에 존재하지 않는 id를 넣으면 해당 카테고리/도시가 존재하지 않는다는 예외처리가 잘 되는데 0을 값으로 넣으면 에러가 뜨네요.. 모임 생성할때는 0도 예외처리가 잘 됐는데 수정할때는 왜 다른지 잘 모르겠습니다

2024-11-12 11:04 UTC, worjs requested changes
리뷰가 늦어서 죄송합니다~~
내내 일정이 있어서 늦게 돌려드렸네요

코멘트 확인해주세요!

2024-11-12 11:04 UTC, worjs commented on src/event/event.service.ts
> +    }
질문주신거는 아마 여기가 답일거같네요
자바스크림트는 조건문에 숫자 0이 들어가면 false로 처리하거든요ㅋㅋㅋ

2024-11-12 11:04 UTC, worjs commented on src/event/event.service.ts
> +    }
두 조건문이 겹치고 있어서 뒤에 조건문은 아예 걸릴 일이 없는 것 같아요.

2024-11-12 11:04 UTC, worjs commented on src/event/event.service.ts
> +    }
시간 처리 꿀팁 드리면
결국 startTime이 payload로 들어온게 있으면 온걸 쓰고 아니면 기존걸 쓰는게 됩니다.
현재 `startime = payload.startTime ??  event.startTime` 이라고 부를 수 있겠죠?
그렇게 결정된 현재의 startTime과 endTime의 정보만 가지고 정합성을 확인하면 됩니다.

2024-11-12 11:04 UTC, worjs commented on src/event/event.service.ts
> +    }
추가로 공연시작 전에는 수정이 아예 안되는 것도 예외처리 해야할 것 같아요

2024-11-12 15:17 UTC, minyoungbaek commented on src/event/event.service.ts
> +    }
아하 그렇군요..! 감사합니다

2024-11-12 15:18 UTC, minyoungbaek commented on src/event/event.service.ts
> +    }
수정하겠습니다!

2024-11-12 15:18 UTC, minyoungbaek commented on src/event/event.service.ts
> +    }
아아 넵 반영하겠습니다!

2024-11-12 16:20 UTC, worjs approved these changes
LGTM!
다음으로 가시죠

2024-11-13 00:43 UTC, merged