모임 지역을 복수로 선택할 수 있도록 변경
minyoungbaek/nest-study-eventory pull request #7
Opened 2024-11-13 05:17 UTC by minyoungbaek

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 모임 지역을 복수로 선택할 수 있도록 변경

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- 1차 migration 전에 prisma schema에 EventCity 테이블 추가한거 리뷰 받겠습니다!

2024-11-13 05:55 UTC, worjs approved these changes
굳굳 가시죠

2024-11-13 10:54 UTC, minyoungbaek commented
cityId 컬럼 데이터 eventCity로 이전하고 schema에서 cityId 컬럼 제거했습니다!

2024-11-13 13:23 UTC, worjs requested changes
고생하셨습니다!

이제 변경하신거 기존 로직 변경 & DTO 변경 해주시면 되겠습니다!
모임 지역이 복수로 바뀌었으니, 내려줄 때도 cityIds, 생성, 수정할때도 cityIds가 되어야 할거예요

2024-11-13 16:10 UTC, minyoungbaek commented
생각보다 수정해야될 부분이 많네요..ㅎㅋㅋ 일단 최대한 할 수 있는만큼 해봤습니다!

2024-11-16 15:05 UTC, worjs requested changes
리뷰 한줄 알고 있었는데 메일을 놓쳤나보네요... ㅠ
혹시 이틀 이상씩 길어지면 디코 dm으로 물어봐주세요ㅠㅠ 죄송합니다

2024-11-16 15:05 UTC, worjs commented on src/event/event.repository.ts
> +        },
이렇게 작성하면 data.cityIds에 undefined를 주면 eventCity가 전부 삭제되지 않을까요?

2024-11-16 15:05 UTC, worjs commented on src/event/dto/event.dto.ts
> +      cityIds: event.eventCity.map((city) => city.cityId),
굿!

2024-11-16 15:05 UTC, worjs commented on src/event/event.repository.ts
> +        },
이거 왜 data.cityIds? 가 되나요?? 타입 상 무조건 존재하는 값일 것 같이지 않나요?

2024-11-16 15:05 UTC, worjs commented on src/event/event.service.ts
> +        }
이렇게 하면 cityIds가 길어질 수록 응답 시간이 길어지게 됩니다.
예를 들어 1000개의 cityIds가 있다고 하면 하나씩 요청하고 기다리고 있으니 2000번의 네트워크 비용이 발생하는거죠.
항상 DB 요청은 최소로! in절을 활용해보시면 좋을 것 같아요.

2024-11-16 15:05 UTC, worjs commented on src/event/event.service.ts
> +      }
undefined  체크가 왜 필요한가요??

2024-11-17 04:47 UTC, minyoungbaek commented on src/event/event.repository.ts
> +        },
아 제대로 확인을 못했네요.. 수정하겠습니다!

2024-11-17 04:48 UTC, minyoungbaek commented on src/event/event.repository.ts
> +        },
그런 경우를 고려를 못했네요ㅠ 한번 반영해보겠습니다

2024-11-17 05:02 UTC, minyoungbaek commented on src/event/event.service.ts
> +      }
음 일단은 저번에 cityId나 categoryId를 0으로 수정하게 되면 예외처리가 제대로 안돼서 undefined가 아닐때 값이 0인 경우와 아닌 경우로 나눠서 예외처리를 해주려고 했습니다..! 먼저 undefined가 아닐때로 구분해줘야 payload.cityId에서 오류가 안떠서 추가했던거 같습니다

2024-11-17 05:02 UTC, minyoungbaek commented on src/event/event.service.ts
> +        }
아아 그렇군요..! 반영해보겠습니다

2024-11-17 10:49 UTC, worjs commented on src/event/event.service.ts
> +      }
어어어음... 여기는 cityId는 없고 cityIds가 있으니까요?

2024-11-17 11:29 UTC, minyoungbaek commented on src/event/event.service.ts
> +      }
아 다시 생각해보니까 여기서는 문제가 안되네요ㅋㅋㅋ 수정해서 다시 올려보겠습니다!

2024-11-17 11:48 UTC, kevvnbk commented
수정했습니다! 바쁘신 와중에 매번 피드백 꼼꼼히 해주셔서 감사합니다~!!

2024-11-17 14:52 UTC, worjs approved these changes
굿! 고생하셧습니다~~
나머지는 수정하고 바로 머지하시면 되겠습니다!!

2024-11-17 14:52 UTC, worjs commented on src/event/event.repository.ts
> +              create: (data.cityIds ?? []).map((cityId) => ({
요기 그냥 data.cityIds.map 으로 될 것 같습니당

2024-11-17 14:52 UTC, worjs commented on src/event/event.service.ts
> +      }
요기 수정된건가요 ㅋㅋㅋ

2024-11-17 14:52 UTC, worjs commented on src/event/event.service.ts
> +      }
지금 생각해보니까 최소 1개의 city 처리는 payload에서 할 수 있을 것 같기도 하네요? 배열 최소 길이 검증하는게 뭐 있었던 듯한....

2024-11-17 15:47 UTC, kevvnbk commented on src/event/event.service.ts
> +      }
patchUpdateEvent에서만 수정하고 createEvent 내에선 안했네용.. 반영하겠습니다! 그리고 찾아보니까 payload에서 @ArrayMinSize(1)로 검증 가능할 수 있겠네요..!

2024-11-17 15:57 UTC, merged