본인 인증 필요한 API 변경, 참여한 모임 목록 조회하는 API
minyoungbaek/nest-study-eventory pull request #8
Opened 2024-11-18 11:11 UTC by kevvnbk

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 본인 인증이 필요한 API들 변경
- 유저가 참여한 모임의 목록을 조회하는 GET /me 메서드 구현

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-18 12:57 UTC, worjs requested changes
POST /events 도 검증이 필요합니다!
그것도 수정해서 올려주세요~

2024-11-18 12:57 UTC, worjs commented on src/event/event.controller.ts
> +  @ApiCreatedResponse({ type: EventListDto })
200 OK!

2024-11-18 12:57 UTC, worjs commented on src/event/event.controller.ts
>    }
얘네들은 payload가 필요 없어지지 않을까요! 인증 정보에서 데이터를 가져다 쓰면 되니까요

2024-11-18 12:57 UTC, worjs commented on src/event/event.service.ts
>      }
이게 필요가 없긴 합니다.
인증 과정 자체가 jwt에 userId만 담아서 주고받고, 받아온 토큰에서 가져온 userId를 DB에서 조회해서 최종적으로 가져오게 되거든요.
이미 유효성 검증이 끝난 유저를 받아오는거라고 보시면 됩니다.
JWTStrategy에 해당 코드가 있습니당

2024-11-18 12:57 UTC, worjs commented on src/event/event.service.ts
> +
이렇게 하면 eventId로 event 가져오는 쿼리를 연속으로 두번 날리는 게 되네요

2024-11-18 14:53 UTC, kevvnbk commented on src/event/event.service.ts
>      }
아아 그렇네용 반영하겠습니다!

2024-11-18 15:42 UTC, minyoungbaek commented on src/event/event.controller.ts
>    }
payload가 필요 없어진다는게 정확히 무슨 뜻인가요..? 그 모임 참가/탈퇴에서는 더이상 payload를 쓸 필요가 없는걸 이해했는데 모임 PATCH 경우에는 어떤 부분에서 필요 없어지는지 이해가 잘 안됩니다..ㅠㅠ

2024-11-18 15:43 UTC, minyoungbaek commented on src/event/event.service.ts
> +
수정해보겠습니다!

2024-11-20 02:14 UTC, minyoungbaek commented
payload 관련 피드백이 이해가 잘안돼서 추가 질문 남겼습니다..! 나머지는 반영해서 올렸습니다 감사합니다!

2024-11-20 09:15 UTC, worjs commented on src/event/event.service.ts
>      }
에 .. 음 user를 검증할 필요가 없습니다! 위의 코멘트 대로긴 한데, 혹시 추가 설명이 필요하실까요?

2024-11-20 09:19 UTC, worjs approved these changes
헉 제가 patch까지 묶어서 코멘트를 달았었군요... 실수였네요..
post만 해당사항이 있습니다.
patch와 delete는 권한체크만 잘 해주면 되구요.

코멘트 다시 보시고 수정하고 머지하시면 될듯! 고생하셨습니다.

2024-11-20 09:19 UTC, worjs commented on src/event/event.service.ts
>        categoryId: payload.categoryId,
네네 이거 맞습니다.
근데 이렇게 된다면 CreateEventPayload에 쓸모가 없어지는 필드가 하나 있죠?

2024-11-20 12:18 UTC, minyoungbaek commented on src/event/event.service.ts
>        categoryId: payload.categoryId,
확인했습니다!

2024-11-20 12:25 UTC, merged